### PR TITLE
home work 6

### PR DESCRIPTION
**Pull request by psergeev**

### CODE REVIEW

**Review by loginov-rocks — CHANGES_REQUESTED** [review]
The routing logic seems good, however there are a few issues.

1. At `/search` and `/film` the header is absent.

Screen Shot 2019-03-30 at 5 14 04 PM

Screen Shot 2019-03-30 at 5 14 57 PM

2. If you open particular movie page you'll not be able to navigate home: https://drive.google.com/open?id=1gezxQbf8auxhQa--YpO7pgqKVmOGZtxg

3. When making search by title the user not able to switch to genres by clicking on buttons, the app doesn't make requests: https://drive.google.com/open?id=1kionHCSF0_gHxWGF7YXvTl9fuuqqycKI

**Comment by psergeev** [comment]
/search and /film now show a search header

**Comment by psergeev** [comment]
Strange but I cant repeat 2 in any browser

**Comment by psergeev** [comment]
Search by genre has been fixed, need to click to genre then click search button.

**Review by loginov-rocks — APPROVED** [review]
Now it works. The second behavior was because of the absent header, now it seems fixed. Well done!

**Pull request merged**
